version: '3.7'

services:
  web:
    build: .
    command: bash -c "
      python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork
  db:
    container_name: db
    image: postgres:9.5
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - djangonetwork
networks:
  djangonetwork:
    driver: bridge
volumes:
  postgres_data:
